# -*- coding: utf-8 -*-
"""Student DataBase Management System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyHfCkQPuVTRDoERFWqHQDPbZ_O3m2iQ
"""

#Student Management
import csv
def Add():
  with open('Students.csv', 'w', newline="") as cF:
    cW = csv.writer(cF)
    cW.writerow(['Name', 'AdmNo','Class','Section','Aggregate','Attendance'])
    while True:
      Name=input("Name:")
      AdmNo=input("Admission Number:")
      Class=input("Class:")
      Section= input("Section:")
      Agg= float(input('Aggregate:'))
      Att= float(input('Attendance:'))
      cW.writerow([Name.upper(), AdmNo.upper(), Class, Section, Agg, Att])
      More=input("More(Y/N)?")
      if More in ['n','N']:
        break
def Modify():
  with open('Students.csv', 'r', newline="") as cF:
    cR= csv.reader(cF, delimiter= ',')
    cW= csv.writer(cF)
    k=[]
    f= list(cR)
    print (f[0])
    k.append(f[0])
    for i in range (1, len(f)):
      print (f[i], end=' ')
      A= input('Modify?(Y/N): ')
      if A in 'Yy':
        a=input("Name:")
        b=input("Admission Number:")
        c=input("Class:")
        d=input("Section:")
        e=input('Aggregate:')
        g=input('Attendance:')
        k.append([a.upper(),b.upper(),c,d,e,g])
      else:
        k.append(f[i])
    with open('Students.csv', 'w', newline="") as cF:
      cW= csv.writer(cF, delimiter=',')
      cW.writerows(k)

def Delete():
   with open('Students.csv', 'r', newline="") as cF:
    cR= csv.reader(cF, delimiter= ',')
    k=[]
    h=0
    f= list(cR)
    print (f[0])
    k.append(f[0])
    for i in range (1, len(f)):
      print (f[i], end=' ')
      A= input('Delete?(Y/N): ')
      if A in 'Nn':
        k.append(f[i])
        h+=1
    if h>0:
      with open('Students.csv', 'w', newline="") as cF:
        cW= csv.writer(cF, delimiter=',')
        cW.writerows(k)

def Display():
  try:
    with open('Students.csv', 'r') as cF:
      cR = csv.reader(cF)
      for r in cR:
        print(r)
  except FileNotFoundError:
    print("Students.csv File Not Found")

def Sort():
  try:
    with open ('Students.csv','r') as cF:
      cR= csv.reader(cF)
      f= list(cR)
      f.sort()
      with open ('Students.csv','w') as cF:
        cW=csv.writer(cF)
        cW.writerows(f)
  except FileNotFoundError:
    print('no file!')

def Result():
  try:
    with open('Students.csv', 'r') as cF:
      cR = csv.reader(cF)
      for r in cR:
        print(r)
  except FileNotFoundError:
    print("Students.csv File Not Found")
def Search():
  try:
    with open('Students.csv', 'r') as cF:
      cR = csv.reader(cF)
      L= list(cR)
      while True:
        J= input('Search by Name (N) or Admission Number (A) or Quit(Q): ')
        if J== 'N':
          Na= input('Enter Name: ')
          Na.upper()
          for i in range (len(L)):
            if L[i][0]== Na:
              print(L[i])
          else:
            print('Name not found')
        elif J=='A':
          Ad= input('Enter AdmNo. : ')
          Ad.upper()
          for i in range (len(L)):
            if L[i][0]==Ad:
              print(L[i])
          else:
            print('Admission Number not found')
        else:
          break
  except FileNotFoundError:
    print("Students.csv File Not Found")

def Menu():
  while True:
    choice= input('Press: E(Enrollment), Ed(Editing), D(Deletion), Di(Display), S(Sorting), R(Result), Search (Sr), Q(Quit): ')
    if choice== 'E':
      Add()
    elif choice== 'Ed':
      Modify()
    elif choice== 'D':
      Delete()
    elif choice== 'Di':
      Display()
    elif choice== 'S':
      Sort()
    elif choice== 'R':
      Result()
    elif choice== 'Sr':
      Search()
    else:
      break

def NewLogin():
  NID= input('Enter new username: ')
  NPASS= input('Enter new password: ')
  CPASS= input('Re-enter password: ')
  if CPASS==NPASS:
    print("Account Created!")
    Menu()
  else:
    N= input('Incorrect. Retry(R) or Create New Login(C)')
    if N=='C':
      NewLogin()
    elif N=='R':
      user= input("enter username: ")
      npass= input('enter password')
      if user==NID and npass==NPASS:
        Menu()
      else:
        print('Sorry! Try Again Later.')

def Admin():
  pas= 'student@loginxx'
  user= 'St.Management'
  us= input("Enter username: ")
  ps= input('Enter password: ')
  if us==user and ps==pas:
    Menu()
  elif us!=user or ps!=pas:
    X= input('Wrong password/username. Retry(R) or Create new login (C) Quit (Q): ')
    if X=='R':
      Admin()
    elif X== 'C':
      NewLogin()
Admin()